# Generated by Django 5.1 on 2024-08-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=15)),
                ('mensagem', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segunda', models.CharField(max_length=100)),
                ('terca', models.CharField(max_length=100)),
                ('quarta', models.CharField(max_length=100)),
                ('quinta', models.CharField(max_length=100)),
                ('sexta', models.CharField(max_length=100)),
                ('sabado', models.CharField(max_length=100)),
                ('domingo', models.CharField(max_length=100)),
            ],
        ),
    ]
