# Generated by Django 5.1 on 2024-08-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adrodolfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domingo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programacao', models.TextField()),
                ('horario', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Quarta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programacao', models.TextField()),
                ('horario', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Quinta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programacao', models.TextField()),
                ('horario', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Sabado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programacao', models.TextField()),
                ('horario', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Segunda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programacao', models.TextField()),
                ('horario', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Sexta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programacao', models.TextField()),
                ('horario', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Terca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programacao', models.TextField()),
                ('horario', models.TimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Escala',
        ),
    ]
