# Generated by Django 5.1 on 2024-11-16 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adrodolfo', '0002_domingo_quarta_quinta_sabado_segunda_sexta_terca_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.TextField()),
                ('programacao', models.TextField()),
                ('horario', models.TimeField()),
                ('congregacao', models.CharField(default='Templo Sede', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Domingo',
        ),
        migrations.DeleteModel(
            name='Quarta',
        ),
        migrations.DeleteModel(
            name='Quinta',
        ),
        migrations.DeleteModel(
            name='Sabado',
        ),
        migrations.DeleteModel(
            name='Segunda',
        ),
        migrations.DeleteModel(
            name='Sexta',
        ),
        migrations.DeleteModel(
            name='Terca',
        ),
    ]
