# Generated by Django 5.1 on 2024-11-16 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adrodolfo', '0003_escala_delete_domingo_delete_quarta_delete_quinta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escala',
            name='congregacao',
            field=models.CharField(choices=[('Templo Sede', 'Templo Sede'), ('Sítio Espinheiro', 'Sítio Espinheiro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='escala',
            name='dia',
            field=models.CharField(choices=[('Segunda-feira', 'Segunda-feira'), ('Terça-feira', 'Terça-feira'), ('Quarta-feira', 'Quarta-feira'), ('Quinta-feira', 'Quinta-feira'), ('Sexta-feira', 'Sexta-feira'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=15),
        ),
    ]
