# Generated by Django 5.1 on 2024-12-02 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adrodolfo', '0005_userblog'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mensagem', models.TextField()),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Contatos',
        ),
        migrations.DeleteModel(
            name='UserBlog',
        ),
    ]
